## Data Understanding

In [1]:
import pandas as pd

df = pd.read_csv(r'data/raw/Google-Playstore.csv')
df.head(5)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,...,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,...,https://webserveis.netlify.app/,webserveis@gmail.com,"May 21, 2020","May 06, 2021",Everyone,https://dev4phones.wordpress.com/licencia-de-uso/,True,False,False,2021-06-15 20:19:35
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50+,50.0,58,True,0.0,...,NaN,vnacrewit@gmail.com,"Aug 9, 2019","Aug 19, 2019",Everyone,https://www.vietnamairlines.com/vn/en/terms-an...,False,False,False,2021-06-15 20:19:35
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10+,10.0,19,True,0.0,...,http://www.climatesmarttech.com/,climatesmarttech2@gmail.com,"Sep 10, 2018","Oct 13, 2018",Everyone,NaN,True,False,False,2021-06-15 20:19:35
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100+,100.0,478,True,0.0,...,http://www.horodyski.com.pl,rmilekhorodyski@gmail.com,"Feb 21, 2020","Nov 12, 2018",Everyone,http://www.horodyski.com.pl,False,False,False,2021-06-15 20:19:35

In [2]:
df.shape

(2312944, 24)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2312944 entries, 0 to 2312943
Data columns (total 24 columns):
 #   Column             Dtype
---  ------             -----
 0   App Name           str
 1   App Id             str
 2   Category           str
 3   Rating             float64
 4   Rating Count       float64
 5   Installs           str
 6   Minimum Installs   float64
 7   Maximum Installs   int64
 8   Free               bool
 9   Price              float64
 10  Currency           str
 11  Size               str
 12  Minimum Android    str
 13  Developer Id       str
 14  Developer Website  str
 15  Developer Email    str
 16  Released           str
 17  Last Updated       str
 18  Content Rating     str
 19  Privacy Policy     str
 20  Ad Supported       bool
 21  In App Purchases   bool
 22  Editors Choice     bool
 23  Scraped Time       str
dtypes: bool(4), float64(4), int64(1), str(15)
memory usage: 875.1 MB

In [4]:
df.describe()

,Rating,Rating Count,Minimum Installs,Maximum Installs,Price
count,2.290061e+06,2.290061e+06,2.312837e+06,2.312944e+06,2.312944e+06
mean,2.203152e+00,2.864839e+03,1.834452e+05,3.202017e+05,1.034992e-01
std,2.106223e+00,2.121626e+05,1.513144e+07,2.355495e+07,2.633127e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,5.000000e+01,8.400000e+01,0.000000e+00
50%,2.900000e+00,6.000000e+00,5.000000e+02,6.950000e+02,0.000000e+00
75%,4.300000e+00,4.200000e+01,5.000000e+03,7.354000e+03,0.000000e+00
max,5.000000e+00,1.385576e+08,1.000000e+10,1.205763e+10,4.000000e+02

In [5]:
df.isnull().sum()

App Name                  5
App Id                    0
Category                  0
Rating                22883
Rating Count          22883
Installs                107
Minimum Installs        107
Maximum Installs          0
Free                      0
Price                     0
Currency                135
Size                    196
Minimum Android        6530
Developer Id             33
Developer Website    760835
Developer Email          31
Released              71053
Last Updated              0
Content Rating            0
Privacy Policy       420953
Ad Supported              0
In App Purchases          0
Editors Choice            0
Scraped Time              0
dtype: int64

In [6]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [7]:
df.head(1)

,app_name,app_id,category,rating,rating_count,installs,minimum_installs,maximum_installs,free,price,...,developer_website,developer_email,released,last_updated,content_rating,privacy_policy,ad_supported,in_app_purchases,editors_choice,scraped_time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,...,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35

In [8]:
import duckdb

con = duckdb.connect("product_analytics.duckdb")
con.register("apps_df", df)

In [9]:
con.execute("""
CREATE OR REPLACE VIEW google_play AS
SELECT *
FROM apps_df;
""")

In [10]:
con.execute("""
select * from google_play limit 5;
""").df()

,app_name,app_id,category,rating,rating_count,installs,minimum_installs,maximum_installs,free,price,...,developer_website,developer_email,released,last_updated,content_rating,privacy_policy,ad_supported,in_app_purchases,editors_choice,scraped_time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,...,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,...,https://webserveis.netlify.app/,webserveis@gmail.com,"May 21, 2020","May 06, 2021",Everyone,https://dev4phones.wordpress.com/licencia-de-uso/,True,False,False,2021-06-15 20:19:35
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50+,50.0,58,True,0.0,...,NaN,vnacrewit@gmail.com,"Aug 9, 2019","Aug 19, 2019",Everyone,https://www.vietnamairlines.com/vn/en/terms-an...,False,False,False,2021-06-15 20:19:35
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10+,10.0,19,True,0.0,...,http://www.climatesmarttech.com/,climatesmarttech2@gmail.com,"Sep 10, 2018","Oct 13, 2018",Everyone,NaN,True,False,False,2021-06-15 20:19:35
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100+,100.0,478,True,0.0,...,http://www.horodyski.com.pl,rmilekhorodyski@gmail.com,"Feb 21, 2020","Nov 12, 2018",Everyone,http://www.horodyski.com.pl,False,False,False,2021-06-15 20:19:35

In [11]:
con.execute("""describe google_play""").df()

          column_name column_type null   key default extra
0            app_name     VARCHAR  YES  None    None  None
1              app_id     VARCHAR  YES  None    None  None
2            category     VARCHAR  YES  None    None  None
3              rating      DOUBLE  YES  None    None  None
4        rating_count      DOUBLE  YES  None    None  None
5            installs     VARCHAR  YES  None    None  None
6    minimum_installs      DOUBLE  YES  None    None  None
7    maximum_installs      BIGINT  YES  None    None  None
8                free     BOOLEAN  YES  None    None  None
9               price      DOUBLE  YES  None    None  None
10           currency     VARCHAR  YES  None    None  None
11               size     VARCHAR  YES  None    None  None
12    minimum_android     VARCHAR  YES  None    None  None
13       developer_id     VARCHAR  YES  None    None  None
14  developer_website     VARCHAR  YES  None    None  None
15    developer_email     VARCHAR  YES  None    None  None
16           released     VARCHAR  YES  None    None  None
17       last_updated     VARCHAR  YES  None    None  None
18     content_rating     VARCHAR  YES  None    None  None
19     privacy_policy     VARCHAR  YES  None    None  None
20       ad_supported     BOOLEAN  YES  None    None  None
21   in_app_purchases     BOOLEAN  YES  None    None  None
22     editors_choice     BOOLEAN  YES  None    None  None
23       scraped_time     VARCHAR  YES  None    None  None

In [12]:
con.execute("""
select 
    count(*) as total_rows,
    count(distinct app_id) as distinct_apps,
    count(distinct app_name) as distinct_app_name
from google_play ;
""").df()

   total_rows  distinct_apps  distinct_app_name
0     2312944        2312944            2177943

In [13]:
con.execute("""
select 
    app_name,
    count(distinct app_id) as distinct_app_ids
from google_play
group by 1
having distinct_app_ids > 1
order by distinct_app_ids desc;
""").df()

                         app_name  distinct_app_ids
0                     Tic Tac Toe               382
1                      Calculator               261
2                      Flashlight               256
3                  BMI Calculator               201
4                  Age Calculator               190
...                           ...               ...
67481  Skin Goku for Minecraft PE                 2
67482             Quick Inventory                 2
67483        French Practice Test                 2
67484          Car Art Wallpapers                 2
67485            Cupcake Keyboard                 2

[67486 rows x 2 columns]

In [14]:
con.execute("""
select 
    *
from google_play
where app_name = 'Tic Tac Toe';
""").df()

,app_name,app_id,category,rating,rating_count,installs,minimum_installs,maximum_installs,free,price,...,developer_website,developer_email,released,last_updated,content_rating,privacy_policy,ad_supported,in_app_purchases,editors_choice,scraped_time
0,Tic Tac Toe,com.dev.atte.tic_tac_toe,Puzzle,0.0,0.0,10+,10.0,30,True,0.0,...,https://ne2ad32ee.app-ads-txt.com,dev.atte.francois@gmail.com,"May 18, 2018","May 18, 2018",Everyone,NaN,True,False,False,2021-06-15 20:23:22
1,Tic Tac Toe,com.md.tictactoe,Board,0.0,0.0,10+,10.0,31,True,0.0,...,NaN,msms.zaman@gmail.com,"Nov 2, 2020","Nov 18, 2020",Everyone,https://smartdailytools.blogspot.com/2020/09/p...,True,False,False,2021-06-15 20:32:58
2,Tic Tac Toe,com.sthirumuru.tictactoenew,Board,4.2,11.0,"5,000+",5000.0,6379,True,0.0,...,NaN,sundeep.thirumuru@gmail.com,"Apr 13, 2021","Jun 03, 2021",Everyone,NaN,True,False,False,2021-06-15 20:44:27
3,Tic Tac Toe,com.fsk00x.TicTacToe,Board,0.0,0.0,500+,500.0,922,True,0.0,...,NaN,devmethyl@outlook.com,"Feb 13, 2020","Feb 13, 2020",Everyone,NaN,True,False,False,2021-06-15 20:47:17
4,Tic Tac Toe,net.snatchdreams.tictactoe,Puzzle,0.0,0.0,10+,10.0,38,True,0.0,...,https://www.snatchdreams.net,snatchdreams@gmail.com,"Jul 16, 2017","Oct 16, 2019",Everyone,https://www.snatchdreams.net/privacy/tic-tac-toe/,True,False,False,2021-06-15 20:50:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,Tic Tac Toe,com.tictactoe.MobileAppsPro,Board,3.8,9269.0,"500,000+",500000.0,800662,True,0.0,...,NaN,smartyka@gmail.com,"Jan 9, 2015","May 20, 2015",Everyone,http://mobileappspro.yolasite.com,True,False,False,2021-06-16 12:23:56
378,Tic Tac Toe,com.erjainam.tictactoe.release,Board,0.0,0.0,50+,50.0,50,True,0.0,...,https://erjainam.com,engineerjainam@gmail.com,"Sep 2, 2018","Sep 02, 2018",Everyone,https://docs.google.com/document/d/1Tyi5D3VxZu...,True,False,False,2021-06-16 12:31:30
379,Tic Tac Toe,com.swapworld.tic_tac_toe,Board,4.7,7.0,10+,10.0,34,True,0.0,...,http://prudhvikchirunomula.pythonanywhere.com/,prudhvik.1996@gmail.com,"Sep 4, 2019","Sep 17, 2019",Everyone,NaN,False,False,False,2021-06-16 12:32:05
380,Tic Tac Toe,com.infuse.tictactoe,Board,4.8,20.0,100+,100.0,462,True,0.0,...,http://www.infuseapps.com,infuseandroidapps@gmail.com,"Jan 18, 2015","Jan 18, 2015",Everyone,NaN,True,False,False,2021-06-16 12:47:11
381,Tic Tac Toe,com.justmailtoavi.avinashk.threet,Puzzle,4.7,10.0,100+,100.0,173,True,0.0,...,NaN,justmailtoavi@gmail.com,"Mar 30, 2016","Apr 01, 2016",Everyone,NaN,False,False,False,2021-06-16 12:57:05

In [15]:
con.execute("""
select 
    count(*) as total_rows,
    count("app_name") as app_name_available,
    count("app_id") as app_id_available,
    count("category") as category_available,
    count("rating") as rating_available,
    count("rating_count") as rating_count_available,
    count("installs") as installs_available
from google_play;
""").df()

,total_rows,app_name_available,app_id_available,category_available,rating_available,rating_count_available,installs_available
0,2312944,2312939,2312944,2312944,2290061,2290061,2312837

In [16]:
con.execute("""
select
    category,
    count(*) as apps,
    round(
        100.0 * count(*) /
        sum(count(*)) over (),
        2
    ) as pct_of_apps
from google_play
group by category
order by apps dESC;
""").df()

                   category    apps  pct_of_apps
0                 Education  241090        10.42
1             Music & Audio  154906         6.70
2                     Tools  143988         6.23
3                  Business  143771         6.22
4             Entertainment  138276         5.98
5                 Lifestyle  118331         5.12
6         Books & Reference  116728         5.05
7           Personalization   89210         3.86
8          Health & Fitness   83510         3.61
9              Productivity   79698         3.45
10                 Shopping   75256         3.25
11             Food & Drink   73927         3.20
12           Travel & Local   67288         2.91
13                  Finance   65466         2.83
14                   Arcade   53792         2.33
15                   Puzzle   51168         2.21
16                   Casual   50813         2.20
17            Communication   48167         2.08
18                   Sports   47483         2.05
19                   Social   44734         1.93
20         News & Magazines   42807         1.85
21              Photography   35552         1.54
22                  Medical   32065         1.39
23                   Action   27555         1.19
24        Maps & Navigation   26722         1.16
25               Simulation   23282         1.01
26                Adventure   23203         1.00
27              Educational   21308         0.92
28             Art & Design   18539         0.80
29          Auto & Vehicles   18280         0.79
30             House & Home   14369         0.62
31  Video Players & Editors   14015         0.61
32                   Events   12841         0.56
33                   Trivia   11795         0.51
34                   Beauty   11772         0.51
35                    Board   10588         0.46
36                   Racing   10362         0.45
37             Role Playing   10034         0.43
38                     Word    8630         0.37
39                 Strategy    8526         0.37
40                     Card    8179         0.35
41                  Weather    7246         0.31
42                   Dating    6524         0.28
43         Libraries & Demo    5198         0.22
44                   Casino    5076         0.22
45                    Music    4202         0.18
46                Parenting    3810         0.16
47                   Comics    2862         0.12

In [17]:
con.execute("""
select 
    min("maximum_installs") as min_installs,
    max("maximum_installs") as max_installs,
    avg("maximum_installs") as avg_installs,
    median("maximum_installs") as median_installs
from google_play;
""").df()

   min_installs  max_installs   avg_installs  median_installs
0             0   12057627016  320201.713137            695.0

In [18]:
con.execute("""
select 
    round(rating, 1) as rating,
    count(*) as apps
from google_play
where rating is not null
group by round(rating, 1)
order by rating;
""").df()

    rating     apps
0      0.0  1059762
1      1.0      713
2      1.1      236
3      1.2      531
4      1.3      579
5      1.4     1011
6      1.5     1157
7      1.6     1644
8      1.7     1928
9      1.8     2957
10     1.9     2588
11     2.0     3804
12     2.1     3675
13     2.2     4954
14     2.3     5414
15     2.4     6051
16     2.5     6942
17     2.6     9213
18     2.7     9200
19     2.8    12235
20     2.9    11522
21     3.0    17275
22     3.1    15539
23     3.2    21485
24     3.3    22613
25     3.4    28908
26     3.5    31636
27     3.6    35989
28     3.7    43300
29     3.8    53863
30     3.9    55684
31     4.0    67342
32     4.1    69723
33     4.2    87993
34     4.3    83276
35     4.4    86304
36     4.5    76753
37     4.6    78302
38     4.7    62205
39     4.8    61109
40     4.9    44524
41     5.0   100122

In [19]:
con.execute("""
select 
    avg(rating) as avg_rating,
    median(rating) as median_rating
from google_play
where rating is not null;
""").df()

   avg_rating  median_rating
0    2.203152            2.9

In [20]:
con.execute("""
select 
    free,
    count(*) as apps,
    round(
        100.0 * count(*) / sum(count(*)) over (),
        2
    ) as percentage
from google_play
group by Free
order by apps desc;
""").df()

    free     apps  percentage
0   True  2267876       98.05
1  False    45068        1.95

In [21]:
con.execute("""
SELECT
    rating,
    COUNT(*) AS apps,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        2
    ) AS pct
FROM google_play
GROUP BY rating
ORDER BY rating;
            """).df()

    rating     apps    pct
0      0.0  1059762  45.82
1      1.0      713   0.03
2      1.1      236   0.01
3      1.2      531   0.02
4      1.3      579   0.03
5      1.4     1011   0.04
6      1.5     1157   0.05
7      1.6     1644   0.07
8      1.7     1928   0.08
9      1.8     2957   0.13
10     1.9     2588   0.11
11     2.0     3804   0.16
12     2.1     3675   0.16
13     2.2     4954   0.21
14     2.3     5414   0.23
15     2.4     6051   0.26
16     2.5     6942   0.30
17     2.6     9213   0.40
18     2.7     9200   0.40
19     2.8    12235   0.53
20     2.9    11522   0.50
21     3.0    17275   0.75
22     3.1    15539   0.67
23     3.2    21485   0.93
24     3.3    22613   0.98
25     3.4    28908   1.25
26     3.5    31636   1.37
27     3.6    35989   1.56
28     3.7    43300   1.87
29     3.8    53863   2.33
30     3.9    55684   2.41
31     4.0    67342   2.91
32     4.1    69723   3.01
33     4.2    87993   3.80
34     4.3    83276   3.60
35     4.4    86304   3.73
36     4.5    76753   3.32
37     4.6    78302   3.39
38     4.7    62205   2.69
39     4.8    61109   2.64
40     4.9    44524   1.92
41     5.0   100122   4.33
42     NaN    22883   0.99

In [22]:
con.execute("""
SELECT
    CASE
        WHEN rating IS NULL THEN 'NULL'
        WHEN rating = 0 THEN 'ZERO'
        ELSE 'POSITIVE'
    END AS rating_status,

    COUNT(*) AS apps,

    SUM(
        CASE
            WHEN rating_count IS NULL THEN 1
            ELSE 0
        END
    ) AS missing_rating_count,

    AVG(rating_count) AS avg_rating_count,
    MEDIAN(rating_count) AS median_rating_count
FROM google_play
GROUP BY rating_status
ORDER BY rating_status;
            """).df()

,rating_status,apps,missing_rating_count,avg_rating_count,median_rating_count
0,NULL,22883,22883.0,NaN,NaN
1,POSITIVE,1230299,0.0,5332.570199,35.0
2,ZERO,1059762,0.0,0.000000,0.0

In [23]:
con.execute("""
SELECT
    COUNT(*) AS total_apps,

    SUM(
        CASE
            WHEN maximum_installs >= 100000000 THEN 1
            ELSE 0
        END
    ) AS apps_100m_plus,

    SUM(
        CASE
            WHEN maximum_installs >= 10000000 THEN 1
            ELSE 0
        END
    ) AS apps_10m_plus,

    SUM(
        CASE
            WHEN maximum_installs >= 1000000 THEN 1
            ELSE 0
        END
    ) AS apps_1m_plus,

    SUM(
        CASE
            WHEN maximum_installs >= 100000 THEN 1
            ELSE 0
        END
    ) AS apps_100k_plus
FROM google_play;
            """).df()

   total_apps  apps_100m_plus  apps_10m_plus  apps_1m_plus  apps_100k_plus
0     2312944           684.0         7700.0       47947.0        185222.0

In [24]:
con.execute("""
SELECT
    CASE
        WHEN maximum_installs < 1000 THEN '<1K'
        WHEN maximum_installs < 10000 THEN '1K-10K'
        WHEN maximum_installs < 100000 THEN '10K-100K'
        WHEN maximum_installs < 1000000 THEN '100K-1M'
        WHEN maximum_installs < 10000000 THEN '1M-10M'
        WHEN maximum_installs < 100000000 THEN '10M-100M'
        ELSE '100M+'
    END AS install_band,

    COUNT(*) AS apps,

    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (),
        2
    ) AS pct_apps
FROM google_play
WHERE maximum_installs IS NOT NULL
GROUP BY install_band
ORDER BY
    CASE install_band
        WHEN '<1K' THEN 1
        WHEN '1K-10K' THEN 2
        WHEN '10K-100K' THEN 3
        WHEN '100K-1M' THEN 4
        WHEN '1M-10M' THEN 5
        WHEN '10M-100M' THEN 6
        WHEN '100M+' THEN 7
    END;
            """).df()

  install_band     apps  pct_apps
0          <1K  1253806     54.21
1       1K-10K   541813     23.43
2     10K-100K   332103     14.36
3      100K-1M   137275      5.94
4       1M-10M    40247      1.74
5     10M-100M     7016      0.30
6        100M+      684      0.03

In [25]:
con.execute("""
SELECT
    category,

    COUNT(*) AS apps,

    MEDIAN(maximum_installs) AS median_installs,

    AVG(maximum_installs) AS avg_installs,

    MAX(maximum_installs) AS max_installs

FROM google_play

WHERE maximum_installs IS NOT NULL

GROUP BY category

ORDER BY median_installs DESC;
            """).df()

,category,apps,median_installs,avg_installs,max_installs
0,Simulation,23282,23782.5,8.571885e+05,189421569
1,Role Playing,10034,19403.5,8.616850e+05,153947521
2,Casino,5076,9228.5,4.379218e+05,95406186
3,Video Players & Editors,14015,7323.0,2.243268e+06,9766230924
4,Card,8179,7301.0,4.084729e+05,129283628
5,Weather,7246,6850.5,6.383209e+05,711617649
6,Comics,2862,5998.0,2.474626e+05,85170436
7,Racing,10362,5876.5,1.649656e+06,780030129
8,Photography,35552,3423.0,8.885846e+05,5754179589
9,Music,4202,3366.0,7.762119e+05,398429863
10,Dating,6524,2677.0,1.991046e+05,286283642
11,Strategy,8526,2300.5,9.021062e+05,643789632
12,Personalization,89210,2297.0,1.959128e+05,2158959897
13,Board,10588,2249.5,4.988241e+05,589524427
14,Word,8630,2229.0,4.013861e+05,110758785
15,Adventure,23203,1842.0,4.231656e+05,427633153
16,Parenting,3810,1609.0,1.275624e+05,36058501
17,Action,27555,1605.0,1.115665e+06,976536041
18,Entertainment,138276,1577.0,2.353619e+05,4605543029
19,Books & Reference,116728,1571.0,8.831964e+04,3202676731
20,Finance,65466,1214.0,1.739140e+05,426398179
21,Tools,143988,1195.0,8.323576e+05,12057627016
22,Trivia,11795,1033.0,1.871741e+05,223749728
23,Puzzle,51168,1025.0,3.745266e+05,274250384
24,Educational,21308,982.0,3.884367e+05,153769168
25,News & Magazines,42807,960.0,2.061493e+05,2961820154
26,Sports,47483,936.0,2.985852e+05,747308036
27,Maps & Navigation,26722,924.5,1.793284e+05,638806478
28,Art & Design,18539,760.0,9.797176e+04,134619454
29,Music & Audio,154906,703.0,1.486187e+05,1067343725
30,Auto & Vehicles,18280,666.0,1.671894e+05,1976625745
31,Education,241090,628.0,4.485557e+04,261431130
32,Social,44734,599.0,7.201878e+05,6782619635
33,Communication,48167,518.0,1.501161e+06,8925640788
34,Libraries & Demo,5198,518.0,1.145199e+05,76374212
35,Casual,50813,502.0,6.007374e+05,1208422684
36,Lifestyle,118331,461.0,8.698819e+04,615144909
37,Travel & Local,67288,448.0,2.755614e+05,9141671889
38,Medical,32065,438.0,3.422049e+04,18243473
39,Productivity,79698,405.0,5.692531e+05,7028265259
40,House & Home,14369,278.0,6.181124e+04,96444714
41,Health & Fitness,83510,277.0,9.661593e+04,1341624888
42,Beauty,11772,259.5,6.046612e+04,53849836
43,Shopping,75256,247.0,1.765745e+05,581776749
44,Arcade,53792,237.0,4.774297e+05,1704495994
45,Business,143771,179.0,5.966283e+04,1410817280
46,Food & Drink,73927,167.0,3.949951e+04,169142236
47,Events,12841,158.0,1.094093e+04,14691214

In [26]:
con.execute("""
SELECT
    category,

    COUNT(*) AS app_count,

    MEDIAN(maximum_installs) AS median_installs,

    SUM(maximum_installs) AS total_installs,

    ROUND(
        SUM(maximum_installs) * 1.0 /
        COUNT(*),
        0
    ) AS installs_per_app

FROM google_play

WHERE maximum_installs IS NOT NULL

GROUP BY category

ORDER BY installs_per_app DESC;
            """).df()

,category,app_count,median_installs,total_installs,installs_per_app
0,Video Players & Editors,14015,7323.0,3.143940e+10,2243268.0
1,Racing,10362,5876.5,1.709374e+10,1649656.0
2,Communication,48167,518.0,7.230640e+10,1501161.0
3,Action,27555,1605.0,3.074214e+10,1115665.0
4,Strategy,8526,2300.5,7.691357e+09,902106.0
5,Photography,35552,3423.0,3.159096e+10,888585.0
6,Role Playing,10034,19403.5,8.646147e+09,861685.0
7,Simulation,23282,23782.5,1.995706e+10,857189.0
8,Tools,143988,1195.0,1.198495e+11,832358.0
9,Music,4202,3366.0,3.261642e+09,776212.0
10,Social,44734,599.0,3.221688e+10,720188.0
11,Weather,7246,6850.5,4.625273e+09,638321.0
12,Casual,50813,502.0,3.052527e+10,600737.0
13,Productivity,79698,405.0,4.536833e+10,569253.0
14,Board,10588,2249.5,5.281549e+09,498824.0
15,Arcade,53792,237.0,2.568190e+10,477430.0
16,Casino,5076,9228.5,2.222891e+09,437922.0
17,Adventure,23203,1842.0,9.818710e+09,423166.0
18,Card,8179,7301.0,3.340900e+09,408473.0
19,Word,8630,2229.0,3.463962e+09,401386.0
20,Educational,21308,982.0,8.276810e+09,388437.0
21,Puzzle,51168,1025.0,1.916378e+10,374527.0
22,Sports,47483,936.0,1.417772e+10,298585.0
23,Travel & Local,67288,448.0,1.854198e+10,275561.0
24,Comics,2862,5998.0,7.082379e+08,247463.0
25,Entertainment,138276,1577.0,3.254490e+10,235362.0
26,News & Magazines,42807,960.0,8.824632e+09,206149.0
27,Dating,6524,2677.0,1.298959e+09,199105.0
28,Personalization,89210,2297.0,1.747738e+10,195913.0
29,Trivia,11795,1033.0,2.207719e+09,187174.0
30,Maps & Navigation,26722,924.5,4.792014e+09,179328.0
31,Shopping,75256,247.0,1.328829e+10,176574.0
32,Finance,65466,1214.0,1.138545e+10,173914.0
33,Auto & Vehicles,18280,666.0,3.056223e+09,167189.0
34,Music & Audio,154906,703.0,2.302193e+10,148619.0
35,Parenting,3810,1609.0,4.860129e+08,127562.0
36,Libraries & Demo,5198,518.0,5.952745e+08,114520.0
37,Art & Design,18539,760.0,1.816299e+09,97972.0
38,Health & Fitness,83510,277.0,8.068397e+09,96616.0
39,Books & Reference,116728,1571.0,1.030938e+10,88320.0
40,Lifestyle,118331,461.0,1.029340e+10,86988.0
41,House & Home,14369,278.0,8.881657e+08,61811.0
42,Beauty,11772,259.5,7.118072e+08,60466.0
43,Business,143771,179.0,8.577785e+09,59663.0
44,Education,241090,628.0,1.081423e+10,44856.0
45,Food & Drink,73927,167.0,2.920080e+09,39500.0
46,Medical,32065,438.0,1.097280e+09,34220.0
47,Events,12841,158.0,1.404925e+08,10941.0

In [27]:
con.execute("""
CREATE OR REPLACE VIEW apps_clean AS

SELECT
    *,
    
    CASE
        WHEN maximum_installs < 1000
            THEN '0-1K'

        WHEN maximum_installs < 10000
            THEN '1K-10K'

        WHEN maximum_installs < 100000
            THEN '10K-100K'

        WHEN maximum_installs < 1000000
            THEN '100K-1M'

        WHEN maximum_installs < 10000000
            THEN '1M-10M'

        WHEN maximum_installs < 100000000
            THEN '10M-100M'

        ELSE '100M+'
    END AS install_band,

    CASE
        WHEN rating > 0
             AND rating_count > 0
        THEN TRUE
        ELSE FALSE
    END AS has_valid_rating

FROM google_play;
            """)

In [28]:
con.execute("""
SELECT
    install_band,

    COUNT(*) AS apps,

    COUNT(*) FILTER (
        WHERE has_valid_rating
    ) AS rated_apps,

    ROUND(
        100.0 *
        COUNT(*) FILTER (WHERE has_valid_rating)
        / COUNT(*),
        2
    ) AS pct_rated,

    ROUND(
        AVG(rating) FILTER (WHERE has_valid_rating),
        2
    ) AS avg_rating,

    MEDIAN(rating) FILTER (
        WHERE has_valid_rating
    ) AS median_rating,

    MEDIAN(rating_count) FILTER (
        WHERE has_valid_rating
    ) AS median_rating_count

FROM apps_clean

GROUP BY install_band

ORDER BY
    CASE install_band
        WHEN '0-1K' THEN 1
        WHEN '1K-10K' THEN 2
        WHEN '10K-100K' THEN 3
        WHEN '100K-1M' THEN 4
        WHEN '1M-10M' THEN 5
        WHEN '10M-100M' THEN 6
        WHEN '100M+' THEN 7
    END;
            """).df()

,install_band,apps,rated_apps,pct_rated,avg_rating,median_rating,median_rating_count
0,0-1K,1253806,264589,21.10,4.47,4.7,9.0
1,1K-10K,541813,461772,85.23,4.03,4.2,20.0
2,10K-100K,332103,320901,96.63,3.95,4.1,125.0
3,100K-1M,137275,135256,98.53,3.97,4.1,1207.0
4,1M-10M,40247,40086,99.60,4.06,4.1,13198.5
5,10M-100M,7016,7012,99.94,4.18,4.2,150902.5
6,100M+,684,683,99.85,4.26,4.3,1519831.0

In [29]:
# Free vs Paid
con.execute("""
SELECT
    CASE
        WHEN maximum_installs >= 1000000
            THEN '1M+'
        ELSE '<1M'
    END AS adoption_segment,

    free,

    COUNT(*) AS apps,

    ROUND(
        100.0 * COUNT(*)
        / SUM(COUNT(*)) OVER (
            PARTITION BY
                CASE
                    WHEN maximum_installs >= 1000000
                        THEN '1M+'
                    ELSE '<1M'
                END
        ),
        2
    ) AS pct_within_segment,

    MEDIAN(maximum_installs) AS median_installs

FROM google_play

GROUP BY
    adoption_segment,
    free

ORDER BY
    adoption_segment,
    free;
""").df()

  adoption_segment   free     apps  pct_within_segment  median_installs
0              1M+  False      105                0.22        1609529.0
1              1M+   True    47842               99.78        2642330.0
2              <1M  False    44963                1.99            258.0
3              <1M   True  2220034               98.01            649.0

In [30]:
# Monetization
con.execute("""
SELECT
    CASE
        WHEN maximum_installs >= 1000000
            THEN '1M+'
        ELSE '<1M'
    END AS adoption_segment,

    in_app_purchases,

    COUNT(*) AS apps,

    ROUND(
        100.0 * COUNT(*)
        / SUM(COUNT(*)) OVER (
            PARTITION BY
                CASE
                    WHEN maximum_installs >= 1000000
                        THEN '1M+'
                    ELSE '<1M'
                END
        ),
        2
    ) AS pct_within_segment

FROM google_play

GROUP BY
    adoption_segment,
    in_app_purchases

ORDER BY
    adoption_segment,
    in_app_purchases;
   """ ).df()

  adoption_segment  in_app_purchases     apps  pct_within_segment
0              1M+             False    26147               54.53
1              1M+              True    21800               45.47
2              <1M             False  2091488               92.34
3              <1M              True   173509                7.66

In [31]:
# Pricing
con.execute("""
SELECT
    CASE
        WHEN maximum_installs >= 1000000
            THEN '1M+'
        ELSE '<1M'
    END AS adoption_segment,

    COUNT(*) AS apps,

    MEDIAN(price) AS median_price,

    AVG(price) AS avg_price,

    MAX(price) AS max_price

FROM google_play

WHERE free = FALSE

GROUP BY adoption_segment;
""").df()

  adoption_segment   apps  median_price  avg_price  max_price
0              1M+    105          2.49   3.153238      19.99
1              <1M  44963          1.99   5.316742     400.00

In [32]:
# Developer analytics
con.execute("""
SELECT
    developer_id,
    COUNT(*) AS app_count
FROM google_play
WHERE developer_id IS NOT NULL
GROUP BY developer_id
ORDER BY app_count DESC
LIMIT 20;
            """).df()

                 developer_id  app_count
0               Subsplash Inc       5422
1                  TRAINERIZE       5153
2                     ChowNow       4865
3                   OrderYOYO       2884
4                     Phorest       2821
5      BH App Development Ltd       2453
6                  Sharefaith       2077
7                    Flipdish       1969
8                  J&M Studio       1942
9                  CyJ Studio       1741
10                    Apptegy       1729
11             +HOME by Ateam       1609
12               Magzter Inc.       1604
13   Branded Apps by MINDBODY       1570
14  Currency Converter X Apps       1520
15                    echurch       1463
16                  Skalpelis       1333
17                  TTMA Apps       1312
18     Virtuagym Professional       1268
19      Branded MINDBODY Apps       1184

In [33]:
# Category Breakout
con.execute("""
SELECT
    category,

    COUNT(*) AS total_apps,

    COUNT(*) FILTER (
        WHERE maximum_installs >= 1000000
    ) AS breakout_apps,

    ROUND(
        100.0 *
        COUNT(*) FILTER (
            WHERE maximum_installs >= 1000000
        )
        / COUNT(*),
        2
    ) AS breakout_rate,

    MEDIAN(maximum_installs) AS median_installs

FROM google_play

GROUP BY category

HAVING COUNT(*) >= 1000

ORDER BY breakout_rate DESC;
""").df()

,category,total_apps,breakout_apps,breakout_rate,median_installs
0,Simulation,23282,2796,12.01,23782.5
1,Racing,10362,1238,11.95,5876.5
2,Role Playing,10034,1158,11.54,19403.5
3,Strategy,8526,685,8.03,2300.5
4,Action,27555,2192,7.95,1605.0
5,Weather,7246,570,7.87,6850.5
6,Video Players & Editors,14015,999,7.13,7323.0
7,Casino,5076,339,6.68,9228.5
8,Card,8179,519,6.35,7301.0
9,Photography,35552,2040,5.74,3423.0
10,Word,8630,444,5.14,2229.0
11,Casual,50813,2581,5.08,502.0
12,Music,4202,205,4.88,3366.0
13,Adventure,23203,1114,4.80,1842.0
14,Board,10588,500,4.72,2249.5
15,Comics,2862,134,4.68,5998.0
16,Educational,21308,991,4.65,982.0
17,Puzzle,51168,1911,3.73,1025.0
18,Arcade,53792,1640,3.05,237.0
19,Tools,143988,4213,2.93,1195.0
20,Sports,47483,1245,2.62,936.0
21,Dating,6524,169,2.59,2677.0
22,Trivia,11795,286,2.42,1033.0
23,Entertainment,138276,3029,2.19,1577.0
24,Parenting,3810,83,2.18,1609.0
25,Finance,65466,1415,2.16,1214.0
26,Communication,48167,1036,2.15,518.0
27,Social,44734,944,2.11,599.0
28,Personalization,89210,1859,2.08,2297.0
29,Maps & Navigation,26722,473,1.77,924.5
30,Libraries & Demo,5198,80,1.54,518.0
31,Productivity,79698,1201,1.51,405.0
32,Shopping,75256,1070,1.42,247.0
33,Art & Design,18539,252,1.36,760.0
34,Auto & Vehicles,18280,215,1.18,666.0
35,Travel & Local,67288,769,1.14,448.0
36,Lifestyle,118331,1262,1.07,461.0
37,News & Magazines,42807,446,1.04,960.0
38,Beauty,11772,119,1.01,259.5
39,Health & Fitness,83510,774,0.93,277.0
40,Music & Audio,154906,1446,0.93,703.0
41,House & Home,14369,119,0.83,278.0
42,Books & Reference,116728,818,0.70,1571.0
43,Education,241090,1519,0.63,628.0
44,Medical,32065,168,0.52,438.0
45,Food & Drink,73927,327,0.44,167.0
46,Business,143771,529,0.37,179.0
47,Events,12841,25,0.19,158.0

## Product Opportunity and scale

In [34]:
# recency updates
con.execute("""
SELECT
    last_updated,
    COUNT(*) AS apps
FROM google_play
GROUP BY last_updated
ORDER BY apps DESC
LIMIT 20;
""").df()

    last_updated   apps
0   Jun 10, 2021  11186
1   Jun 11, 2021  10514
2   Jun 09, 2021  10210
3   Jun 14, 2021   9957
4   Jun 08, 2021   9844
5   Jun 07, 2021   9815
6   Jun 15, 2021   9104
7   Jun 03, 2021   8748
8   Jun 02, 2021   8644
9   Jun 01, 2021   8503
10  Jun 04, 2021   8466
11  May 31, 2021   7620
12  May 27, 2021   7523
13  May 28, 2021   7154
14  May 21, 2021   7052
15  May 25, 2021   7023
16  May 19, 2021   6796
17  May 20, 2021   6759
18  Apr 30, 2021   6734
19  May 26, 2021   6676

In [35]:
# Developer scale 
con.execute("""
WITH developer_apps AS (

    SELECT
        developer_id,
        COUNT(*) AS developer_app_count
    FROM google_play
    WHERE developer_id IS NOT NULL
    GROUP BY developer_id

),

apps AS (

    SELECT
        g.*,
        d.developer_app_count
    FROM google_play g
    LEFT JOIN developer_apps d
        ON g.developer_id = d.developer_id
)

SELECT

    CASE
        WHEN developer_app_count = 1 THEN '1 app'
        WHEN developer_app_count BETWEEN 2 AND 5 THEN '2-5 apps'
        WHEN developer_app_count BETWEEN 6 AND 10 THEN '6-10 apps'
        WHEN developer_app_count BETWEEN 11 AND 50 THEN '11-50 apps'
        ELSE '50+ apps'
    END AS developer_segment,

    COUNT(*) AS apps,

    COUNT(*) FILTER (
        WHERE maximum_installs >= 1000000
    ) AS breakout_apps,

    ROUND(
        100.0 *
        COUNT(*) FILTER (
            WHERE maximum_installs >= 1000000
        ) / COUNT(*),
        2
    ) AS breakout_rate

FROM apps

GROUP BY 1

ORDER BY breakout_rate DESC;
""").df()

  developer_segment    apps  breakout_apps  breakout_rate
0         6-10 apps  247294           7787           3.15
1        11-50 apps  509018          15095           2.97
2          2-5 apps  560402          13128           2.34
3             1 app  490445           7046           1.44
4          50+ apps  505785           4891           0.97

In [36]:
# Category Opportunity Matrix
con.execute("""
SELECT
    category,

    COUNT(*) AS app_count,

    MEDIAN(maximum_installs) AS median_installs,

    QUANTILE_CONT(maximum_installs, 0.75)
        AS p75_installs,

    QUANTILE_CONT(maximum_installs, 0.90)
        AS p90_installs,

    ROUND(
        100.0 *
        COUNT(*) FILTER (
            WHERE maximum_installs >= 100000
        ) / COUNT(*),
        2
    ) AS pct_100k_plus,

    ROUND(
        100.0 *
        COUNT(*) FILTER (
            WHERE maximum_installs >= 1000000
        ) / COUNT(*),
        2
    ) AS breakout_rate,

    MEDIAN(rating) FILTER (
        WHERE rating > 0
          AND rating_count > 0
    ) AS median_rating,

    MEDIAN(rating_count) FILTER (
        WHERE rating > 0
          AND rating_count > 0
    ) AS median_rating_count

FROM google_play

GROUP BY category

HAVING COUNT(*) >= 5000

ORDER BY median_installs DESC;
""").df()

,category,app_count,median_installs,p75_installs,p90_installs,pct_100k_plus,breakout_rate,median_rating,median_rating_count
0,Simulation,23282,23782.5,254001.00,1321251.0,35.16,12.01,3.9,232.0
1,Role Playing,10034,19403.5,221701.75,1267069.4,33.24,11.54,4.0,366.0
2,Casino,5076,9228.5,79468.25,555897.0,22.91,6.68,4.2,140.0
3,Video Players & Editors,14015,7323.0,65029.00,535160.4,21.13,7.13,3.9,86.0
4,Card,8179,7301.0,77329.50,500022.0,22.85,6.35,4.1,131.0
5,Weather,7246,6850.5,76259.00,670444.0,22.73,7.87,4.2,119.0
6,Racing,10362,5876.5,142276.75,1417167.2,27.78,11.95,4.0,109.0
7,Photography,35552,3423.0,39067.00,352347.1,17.68,5.74,4.0,57.0
8,Dating,6524,2677.0,20444.50,129803.1,11.57,2.59,3.9,54.0
9,Strategy,8526,2300.5,57202.00,678077.0,21.08,8.03,4.1,130.0
10,Personalization,89210,2297.0,18408.75,109364.9,10.56,2.08,4.3,50.0
11,Board,10588,2249.5,29126.50,257498.9,15.41,4.72,4.1,60.0
12,Word,8630,2229.0,28247.00,287732.4,15.82,5.14,4.3,69.0
13,Adventure,23203,1842.0,26486.50,251879.8,14.97,4.80,4.1,89.0
14,Action,27555,1605.0,40598.50,613580.6,19.52,7.95,4.0,68.0
15,Entertainment,138276,1577.0,14618.25,104584.5,10.28,2.19,4.1,39.0
16,Books & Reference,116728,1571.0,11762.00,56116.4,6.38,0.70,4.4,40.0
17,Finance,65466,1214.0,11460.50,85433.0,9.20,2.16,4.1,50.0
18,Tools,143988,1195.0,12759.00,113472.6,10.66,2.93,4.1,43.0
19,Trivia,11795,1033.0,11321.50,104882.8,10.26,2.42,4.2,44.0
20,Puzzle,51168,1025.0,11347.50,136677.4,11.32,3.73,4.3,42.0
21,Educational,21308,982.0,14515.00,173607.9,12.61,4.65,4.2,38.0
22,News & Magazines,42807,960.0,7043.00,43147.8,5.98,1.04,4.3,32.0
23,Sports,47483,936.0,9038.00,77425.0,8.84,2.62,4.2,39.0
24,Maps & Navigation,26722,924.5,8494.75,60921.5,7.69,1.77,4.0,41.0
25,Art & Design,18539,760.0,7109.00,48582.6,6.62,1.36,4.1,29.0
26,Music & Audio,154906,703.0,5446.00,33481.0,4.99,0.93,4.4,29.0
27,Auto & Vehicles,18280,666.0,5292.75,36107.9,5.86,1.18,4.0,28.0
28,Education,241090,628.0,5240.00,33820.1,4.78,0.63,4.3,29.0
29,Social,44734,599.0,6368.75,58314.0,7.59,2.11,4.3,34.0
30,Communication,48167,518.0,5663.00,56791.4,7.56,2.15,4.2,31.0
31,Libraries & Demo,5198,518.0,4963.25,45373.6,6.69,1.54,4.2,28.0
32,Casual,50813,502.0,11387.00,230055.0,13.43,5.08,4.2,37.0
33,Lifestyle,118331,461.0,5102.00,43878.0,6.30,1.07,4.3,31.0
34,Travel & Local,67288,448.0,3401.00,25568.3,4.78,1.14,4.2,24.0
35,Medical,32065,438.0,3741.00,25035.0,4.11,0.52,4.2,26.0
36,Productivity,79698,405.0,3883.75,35060.4,6.00,1.51,4.2,29.0
37,House & Home,14369,278.0,2064.00,14784.2,3.41,0.83,4.0,21.0
38,Health & Fitness,83510,277.0,2709.00,24436.2,4.65,0.93,4.2,27.0
39,Beauty,11772,259.5,2407.25,22768.0,4.86,1.01,4.2,23.0
40,Shopping,75256,247.0,2281.25,21013.5,4.75,1.42,4.3,23.0
41,Arcade,53792,237.0,2966.50,48615.2,7.62,3.05,4.3,22.0
42,Business,143771,179.0,1229.00,8191.0,2.06,0.37,4.2,18.0
43,Food & Drink,73927,167.0,1009.00,6552.8,2.15,0.44,4.3,18.0
44,Events,12841,158.0,701.00,3497.0,1.06,0.19,4.5,14.0

### Final Opportunity Score

In [37]:
con.execute("""
CREATE OR REPLACE VIEW category_opportunity AS

WITH category_metrics AS (

    SELECT
        category,

        COUNT(*) AS app_count,

        MEDIAN(maximum_installs) AS median_installs,

        100.0 *
        COUNT(*) FILTER (
            WHERE maximum_installs >= 1000000
        ) / COUNT(*) AS breakout_rate,

        100.0 *
        COUNT(*) FILTER (
            WHERE maximum_installs >= 100000
        ) / COUNT(*) AS pct_100k_plus,

        MEDIAN(rating) FILTER (
            WHERE rating > 0
              AND rating_count > 0
        ) AS median_rating

    FROM google_play

    GROUP BY category

    HAVING COUNT(*) >= 5000
),

ranked AS (

    SELECT
        *,

        PERCENT_RANK() OVER (
            ORDER BY median_installs
        ) AS demand_score,

        PERCENT_RANK() OVER (
            ORDER BY breakout_rate
        ) AS breakout_score,

        PERCENT_RANK() OVER (
            ORDER BY pct_100k_plus
        ) AS scale_score,

        PERCENT_RANK() OVER (
            ORDER BY median_rating
        ) AS quality_score,

        1 - PERCENT_RANK() OVER (
            ORDER BY app_count
        ) AS supply_score

    FROM category_metrics
)

SELECT

    category,

    app_count,

    ROUND(median_installs, 0) AS median_installs,

    ROUND(breakout_rate, 2) AS breakout_rate,

    ROUND(pct_100k_plus, 2) AS pct_100k_plus,

    ROUND(median_rating, 2) AS median_rating,

    ROUND(
          100 * (
              0.30 * demand_score
            + 0.25 * breakout_score
            + 0.20 * scale_score
            + 0.15 * quality_score
            + 0.10 * supply_score
          ),
          2
    ) AS opportunity_score

FROM ranked

ORDER BY opportunity_score DESC;
""").df()

Empty DataFrame
Columns: [Count]
Index: []

### Demand to Supply efficiency

In [38]:
con.execute("""
SELECT

    category,

    COUNT(*) AS app_count,

    MEDIAN(maximum_installs) AS median_installs,

    ROUND(
        MEDIAN(maximum_installs) /
        COUNT(*),
        2
    ) AS demand_supply_efficiency,

    ROUND(
        100.0 *
        COUNT(*) FILTER (
            WHERE maximum_installs >= 1000000
        ) / COUNT(*),
        2
    ) AS breakout_rate

FROM google_play

GROUP BY category

HAVING COUNT(*) >= 5000

ORDER BY demand_supply_efficiency DESC;
""").df()

,category,app_count,median_installs,demand_supply_efficiency,breakout_rate
0,Role Playing,10034,19403.5,1.93,11.54
1,Casino,5076,9228.5,1.82,6.68
2,Simulation,23282,23782.5,1.02,12.01
3,Weather,7246,6850.5,0.95,7.87
4,Card,8179,7301.0,0.89,6.35
5,Racing,10362,5876.5,0.57,11.95
6,Video Players & Editors,14015,7323.0,0.52,7.13
7,Dating,6524,2677.0,0.41,2.59
8,Strategy,8526,2300.5,0.27,8.03
9,Word,8630,2229.0,0.26,5.14
10,Board,10588,2249.5,0.21,4.72
11,Photography,35552,3423.0,0.10,5.74
12,Libraries & Demo,5198,518.0,0.10,1.54
13,Trivia,11795,1033.0,0.09,2.42
14,Adventure,23203,1842.0,0.08,4.80
15,Action,27555,1605.0,0.06,7.95
16,Educational,21308,982.0,0.05,4.65
17,Auto & Vehicles,18280,666.0,0.04,1.18
18,Art & Design,18539,760.0,0.04,1.36
19,Maps & Navigation,26722,924.5,0.03,1.77
20,Personalization,89210,2297.0,0.03,2.08
21,Sports,47483,936.0,0.02,2.62
22,House & Home,14369,278.0,0.02,0.83
23,Beauty,11772,259.5,0.02,1.01
24,News & Magazines,42807,960.0,0.02,1.04
25,Puzzle,51168,1025.0,0.02,3.73
26,Finance,65466,1214.0,0.02,2.16
27,Events,12841,158.0,0.01,0.19
28,Social,44734,599.0,0.01,2.11
29,Casual,50813,502.0,0.01,5.08
30,Entertainment,138276,1577.0,0.01,2.19
31,Medical,32065,438.0,0.01,0.52
32,Books & Reference,116728,1571.0,0.01,0.70
33,Communication,48167,518.0,0.01,2.15
34,Tools,143988,1195.0,0.01,2.93
35,Travel & Local,67288,448.0,0.01,1.14
36,Productivity,79698,405.0,0.01,1.51
37,Business,143771,179.0,0.00,0.37
38,Music & Audio,154906,703.0,0.00,0.93
39,Arcade,53792,237.0,0.00,3.05
40,Education,241090,628.0,0.00,0.63
41,Shopping,75256,247.0,0.00,1.42
42,Food & Drink,73927,167.0,0.00,0.44
43,Health & Fitness,83510,277.0,0.00,0.93
44,Lifestyle,118331,461.0,0.00,1.07

In [39]:
con.execute("""
SELECT *
FROM category_opportunity
ORDER BY opportunity_score DESC;
""").df()

,category,app_count,median_installs,breakout_rate,pct_100k_plus,median_rating,opportunity_score
0,Casino,5076,9229.0,6.68,22.91,4.2,84.43
1,Role Playing,10034,19404.0,11.54,33.24,4.0,82.16
2,Weather,7246,6851.0,7.87,22.73,4.2,81.93
3,Simulation,23282,23783.0,12.01,35.16,3.9,80.68
4,Racing,10362,5877.0,11.95,27.78,4.0,78.64
5,Card,8179,7301.0,6.35,22.85,4.1,78.41
6,Strategy,8526,2301.0,8.03,21.08,4.1,76.25
7,Word,8630,2229.0,5.14,15.82,4.3,76.14
8,Video Players & Editors,14015,7323.0,7.13,21.13,3.9,73.86
9,Photography,35552,3423.0,5.74,17.68,4.0,66.82
10,Board,10588,2250.0,4.72,15.41,4.1,66.48
11,Action,27555,1605.0,7.95,19.52,4.0,65.80
12,Adventure,23203,1842.0,4.80,14.97,4.1,63.18
13,Dating,6524,2677.0,2.59,11.57,3.9,61.48
14,Puzzle,51168,1025.0,3.73,11.32,4.3,59.89
15,Educational,21308,982.0,4.65,12.61,4.2,58.64
16,Personalization,89210,2297.0,2.08,10.56,4.3,58.30
17,Trivia,11795,1033.0,2.42,10.26,4.2,55.23
18,Casual,50813,502.0,5.08,13.43,4.2,50.80
19,Sports,47483,936.0,2.62,8.84,4.2,49.32
20,Tools,143988,1195.0,2.93,10.66,4.1,49.20
21,Entertainment,138276,1577.0,2.19,10.28,4.1,48.52
22,Finance,65466,1214.0,2.16,9.20,4.1,47.73
23,Social,44734,599.0,2.11,7.59,4.3,45.45
24,Books & Reference,116728,1571.0,0.70,6.38,4.4,44.43
25,Libraries & Demo,5198,518.0,1.54,6.69,4.2,42.16
26,News & Magazines,42807,960.0,1.04,5.98,4.3,41.59
27,Arcade,53792,237.0,3.05,7.62,4.3,41.14
28,Maps & Navigation,26722,925.0,1.77,7.69,4.0,39.89
29,Communication,48167,518.0,2.15,7.56,4.2,38.98
30,Art & Design,18539,760.0,1.36,6.62,4.1,37.95
31,Music & Audio,154906,703.0,0.93,4.99,4.4,35.91
32,Lifestyle,118331,461.0,1.07,6.30,4.3,32.16
33,Auto & Vehicles,18280,666.0,1.18,5.86,4.0,31.59
34,Productivity,79698,405.0,1.51,6.00,4.2,28.64
35,Education,241090,628.0,0.63,4.78,4.3,27.27
36,Shopping,75256,247.0,1.42,4.75,4.3,27.16
37,Beauty,11772,260.0,1.01,4.86,4.2,26.48
38,Travel & Local,67288,448.0,1.14,4.78,4.2,26.14
39,Events,12841,158.0,0.19,1.06,4.5,22.27
40,Medical,32065,438.0,0.52,4.11,4.2,20.80
41,Health & Fitness,83510,277.0,0.93,4.65,4.2,18.30
42,House & Home,14369,278.0,0.83,3.41,4.0,17.39
43,Food & Drink,73927,167.0,0.44,2.15,4.3,16.14
44,Business,143771,179.0,0.37,2.06,4.2,9.20

### Simulation Market Distribution

In [40]:
con.execute("""
SELECT
    CASE
        WHEN maximum_installs < 1000 THEN '<1K'
        WHEN maximum_installs < 10000 THEN '1K-10K'
        WHEN maximum_installs < 100000 THEN '10K-100K'
        WHEN maximum_installs < 1000000 THEN '100K-1M'
        WHEN maximum_installs < 10000000 THEN '1M-10M'
        WHEN maximum_installs < 100000000 THEN '10M-100M'
        ELSE '100M+'
    END AS install_band,

    COUNT(*) AS apps,

    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (),
        2
    ) AS pct_apps,

    MEDIAN(rating) AS median_rating,

    MEDIAN(rating_count) AS median_rating_count

FROM google_play

WHERE category = 'Simulation'

GROUP BY install_band

ORDER BY
    CASE install_band
        WHEN '<1K' THEN 1
        WHEN '1K-10K' THEN 2
        WHEN '10K-100K' THEN 3
        WHEN '100K-1M' THEN 4
        WHEN '1M-10M' THEN 5
        WHEN '10M-100M' THEN 6
        WHEN '100M+' THEN 7
    END;
""").df()

  install_band  apps  pct_apps  median_rating  median_rating_count
0          <1K  4734     20.33            0.0                  0.0
1       1K-10K  4789     20.57            3.7                 19.0
2     10K-100K  5572     23.93            3.8                133.0
3      100K-1M  5391     23.16            3.8               1208.0
4       1M-10M  2412     10.36            4.0              11052.0
5     10M-100M   371      1.59            4.1             171376.0
6        100M+    13      0.06            4.2            1215739.0

### Simulation Winners

In [41]:
con.execute(""" 
SELECT
    app_name,
    developer_id,
    rating,
    rating_count,
    maximum_installs,
    free,
    price,
    in_app_purchases,
    editors_choice,
    last_updated
FROM google_play
WHERE category = 'Simulation'
ORDER BY maximum_installs DESC
LIMIT 50;
""").df()

,app_name,developer_id,rating,rating_count,maximum_installs,free,price,in_app_purchases,editors_choice,last_updated
0,The Sims FreePlay,ELECTRONIC ARTS,4.0,5545972.0,189421569,True,0.0,True,False,"Jun 11, 2021"
1,Vegas Crime Simulator,Naxeex Ltd,4.2,1215739.0,172102967,True,0.0,True,False,"May 27, 2021"
2,Dragon City Mobile,Socialpoint,4.6,8424191.0,165592452,True,0.0,True,True,"Jun 10, 2021"
3,Bike Stunt Race 3d Bike Racing Games – Bike game,The Knights Pvt Ltd,4.1,172583.0,124499897,True,0.0,True,False,"May 22, 2021"
4,Episode - Choose Your Story,Episode Interactive,4.3,3636696.0,122869683,True,0.0,True,False,"Jun 09, 2021"
5,Woodturning,VOODOO,4.0,442785.0,121407479,True,0.0,True,False,"May 27, 2021"
6,2 3 4 Player Mini Games,Better World Games,4.4,715936.0,115689781,True,0.0,False,False,"Apr 27, 2021"
7,Truck Simulator 2018 : Europe,Zuuks Games,4.2,771009.0,114238047,True,0.0,True,False,"Nov 23, 2020"
8,Farming Simulator 14,GIANTS Software,4.2,916524.0,107348637,True,0.0,True,False,"Jul 17, 2017"
9,SimCity BuildIt,ELECTRONIC ARTS,4.3,5219332.0,106874506,True,0.0,True,True,"Jun 08, 2021"
10,Scary Teacher 3D,Z & K Games,4.3,1284750.0,106348611,True,0.0,True,False,"May 05, 2021"
11,Plague Inc.,Miniclip.com,4.5,3528894.0,101937686,True,0.0,True,False,"Mar 02, 2021"
12,Flight Simulator: Fly Plane 3D,i6 Games,4.0,709281.0,101095621,True,0.0,False,False,"Mar 01, 2017"
13,Idle Miner Tycoon: Mine & Money Clicker Manage...,Kolibri Games,4.6,3350730.0,98455942,True,0.0,True,True,"Jun 11, 2021"
14,Craftsman: Building Craft,StarGame22,4.2,1318731.0,98113012,True,0.0,False,False,"Jun 12, 2019"
15,Bus Simulator : Ultimate,Zuuks Games,4.3,1258961.0,97410645,True,0.0,True,False,"May 04, 2021"
16,Perfect Slices,SayGames,4.2,277384.0,88437654,True,0.0,True,False,"Feb 23, 2021"
17,Taxi Game 2,baklabs,4.2,356382.0,88263890,True,0.0,True,False,"Aug 27, 2020"
18,Dragon Mania Legends,Gameloft SE,4.5,2774744.0,87292468,True,0.0,True,True,"Jun 07, 2021"
19,Bus Simulator: Original,Ovidiu Pop,4.0,1487624.0,87118965,True,0.0,True,False,"Sep 04, 2020"
20,Taxi Game,baklabs,3.4,501389.0,84016666,True,0.0,False,False,"Aug 05, 2020"
21,Tie Dye,Crazy Labs by TabTale,4.1,320908.0,83448147,True,0.0,False,False,"Jun 03, 2021"
22,"Real Cake Maker 3D - Bake, Design & Decorate",Coco Play By TabTale,4.2,275146.0,82542164,True,0.0,True,False,"Apr 06, 2021"
23,Modern Car Parking 3D & Driving Games - Car Games,The Knights Pvt Ltd,4.1,140984.0,81650606,True,0.0,True,False,"Jun 11, 2021"
24,Dog Run - Pet Dog Game Simulator,Green Tea Games,4.1,176004.0,75497048,True,0.0,True,False,"May 20, 2021"
25,Raft Survival: Ocean Nomad - Simulator,TREASTONE LTD,4.4,60820.0,73659085,True,0.0,True,False,"Jun 10, 2021"
26,Jurassic World™: The Game,Ludia Inc.,4.1,1658032.0,71324901,True,0.0,True,False,"May 27, 2021"
27,ASMR Slicing,Crazy Labs by TabTale,3.9,155890.0,70748761,True,0.0,True,False,"Jun 14, 2021"
28,The Sims™ Mobile,ELECTRONIC ARTS,4.1,1402266.0,69364620,True,0.0,True,True,"Jun 14, 2021"
29,City Flight Airplane Pilot New Game - Plane Games,The Knights Pvt Ltd,4.0,121162.0,69062831,True,0.0,True,False,"Jun 14, 2021"
30,Phone Case DIY,Crazy Labs by TabTale,3.9,210627.0,68551663,True,0.0,False,False,"Jun 09, 2021"
31,Disney Magic Kingdoms: Build Your Own Magical ...,Gameloft SE,3.9,625504.0,65390302,True,0.0,True,False,"Jun 11, 2021"
32,Fishing Clash,Ten Square Games,4.7,1364213.0,64664242,True,0.0,True,False,"Jun 01, 2021"
33,Barbie Dreamhouse Adventures,Budge Studios,4.2,806700.0,64505946,True,0.0,True,False,"May 07, 2021"
34,Bus Simulator Indonesia,Maleo,4.4,1936780.0,63947633,True,0.0,False,False,"Jan 11, 2021"
35,Sushi Roll 3D - Cooking ASMR Game,SayGames,4.0,236064.0,63804522,True,0.0,True,False,"May 12, 2021"
36,Clean Road,SayGames Ltd,4.2,931393.0,63798380,True,0.0,True,False,"Jan 14, 2021"
37,Euro Truck Evolution (Simulator),Ovidiu Pop,4.1,1126618.0,63588275,True,0.0,True,False,"May 07, 2019"
38,Cut and Paint,Good Job Games,4.0,148854.0,60638328,True,0.0,True,False,"Nov 26, 2020"
39,Soap Cutting - Satisfying ASMR,Crazy Labs by TabTale,4.0,105535.0,59881254,True,0.0,True,False,"May 12, 2021"
40,Drive and Park,SayGames,4.3,608360.0,59316720,True,0.0,True,False,"Apr 13, 2021"
41,Car Parking Multiplayer,olzhass,4.4,988270.0,57959930,True,0.0,True,False,"May 19, 2021"
42,Design Home: House Renovation,Crowdstar Inc,4.2,1058297.0,56975412,True,0.0,True,True,"Jun 01, 2021"
43,Turbo Dismount™,Secret Exit Ltd.,4.2,766065.0,56972883,True,0.0,True,False,"Apr 26, 2019"
44,WildCraft: Animal Sim Online 3D,Turbo Rocket Games,4.5,78740.0,56870503,True,0.0,True,False,"May 05, 2021"
45,Harvest.io – Farming Arcade in 3D,CASUAL AZUR GAMES,4.2,114135.0,56807109,True,0.0,True,False,"May 31, 2021"
46,Mobile Bus Simulator,LOCOS,4.2,393638.0,54705045,True,0.0,True,False,"Aug 01, 2020"
47,Acrylic Nails!,Crazy Labs by TabTale,3.7,144840.0,53708434,True,0.0,False,False,"Jun 02, 2021"
48,Dragons: Rise of Berk,Ludia Inc.,4.4,1517742.0,53291326,True,0.0,True,False,"May 31, 2021"
49,Weaphones™ Gun Sim Free Vol 1,OranginalPlan,4.3,651815.0,51547015,True,0.0,False,False,"Jan 17, 2018"

### Monetization

In [42]:
con.execute("""
SELECT
    in_app_purchases,
    COUNT(*) AS apps,

    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (),
        2
    ) AS pct_apps,

    MEDIAN(maximum_installs) AS median_installs,

    MEDIAN(rating_count) AS median_rating_count

FROM google_play

WHERE category = 'Simulation'

GROUP BY in_app_purchases
ORDER BY median_installs DESC;
""").df()

   in_app_purchases   apps  pct_apps  median_installs  median_rating_count
0              True   7265      31.2         126601.0                715.0
1             False  16017      68.8          10703.0                 49.5

### Simulation Breakout vs Non Breakout

In [43]:
con.execute("""
WITH simulation_apps AS (

    SELECT
        *,
        CASE
            WHEN maximum_installs >= 1000000
            THEN 'Breakout'
            ELSE 'Non-Breakout'
        END AS adoption_segment

    FROM google_play

    WHERE category = 'Simulation'
)

SELECT

    adoption_segment,

    COUNT(*) AS apps,

    ROUND(AVG(rating), 2) AS avg_rating,

    MEDIAN(rating_count) AS median_rating_count,

    MEDIAN(maximum_installs) AS median_installs,

    ROUND(
        100.0 * COUNT(*) FILTER (
            WHERE in_app_purchases = TRUE
        ) / COUNT(*),
        2
    ) AS pct_iap,

    ROUND(
        100.0 * COUNT(*) FILTER (
            WHERE free = TRUE
        ) / COUNT(*),
        2
    ) AS pct_free

FROM simulation_apps

GROUP BY adoption_segment;
""").df()

,adoption_segment,apps,avg_rating,median_rating_count,median_installs,pct_iap,pct_free
0,Breakout,2796,3.94,14305.0,2558036.0,59.44,99.79
1,Non-Breakout,20486,3.11,65.0,13205.0,27.35,96.83